import test from 'node:test';
import assert from 'node:assert/strict';
import { validateNestedProcedureV1 } from '../dist/quant-core/research/nested-validation.js';
function prediction(t, y, cal, base, raw = cal) { return { asset: 'XAUUSD', decisionTime: t, actualLabel: y, rawProbability: raw, calibratedProbability: cal, baselineProbability: base }; }
function goodFold(i, overrides = {}) { const start = i * 100; const predictions = overrides.predictions ?? [prediction(start + 1, 0, 0.2, 0.6), prediction(start + 2, 1, 0.8, 0.6), prediction(start + 3, 0, 0.2, 0.6), prediction(start + 4, 1, 0.8, 0.6)]; return { outerFoldId: `OF_${i + 1}`, selectionStatus: 'SELECTED', predictions, retentionRate: 0.8, ...overrides }; }
function sixGood() { return Array.from({ length: 6 }, (_, i) => goodFold(i)); }
test('Nested requires exactly six outer folds in V1', () => { const res = validateNestedProcedureV1(sixGood().slice(0, 5)); assert.equal(res.status, 'NOT_VALIDATED_V1'); assert(res.rejectionReasons.includes('OUTER_FOLD_COUNT_MISMATCH')); });
test('Any outer NO_VALID selection forces NOT_VALIDATED_V1', () => { const folds = sixGood(); folds[2] = { outerFoldId: 'OF_3', selectionStatus: 'NO_VALID_LABEL_SPEC_V1' }; const res = validateNestedProcedureV1(folds); assert.equal(res.status, 'NOT_VALIDATED_V1'); assert(res.rejectionReasons.includes('OUTER_NO_VALID_SELECTION')); });
test('Outer OOS duplicate (asset, decisionTime) is rejected', () => { const folds = sixGood(); folds[1].predictions = [prediction(1, 0, 0.2, 0.6), prediction(102, 1, 0.8, 0.6)]; const res = validateNestedProcedureV1(folds); assert.equal(res.status, 'NOT_VALIDATED_V1'); assert(res.rejectionReasons.some((r) => r.startsWith('DUPLICATE_OUTER_OOS_PREDICTION'))); });
test('Invalid outer probabilities produce NOT_VALIDATED_V1 rather than throwing', () => { const folds = sixGood(); folds[0].predictions = [prediction(1, 0, Number.NaN, 0.5), prediction(2, 1, 0.8, 0.5)]; const res = validateNestedProcedureV1(folds); assert.equal(res.status, 'NOT_VALIDATED_V1'); assert(res.rejectionReasons.includes('INVALID_OUTER_PREDICTION:OF_1')); });
test('Global BrierSkill <= 0 rejects nested validation', () => { const folds = Array.from({ length: 6 }, (_, i) => goodFold(i, { predictions: [prediction(i * 100 + 1, 0, 0.95, 0.5), prediction(i * 100 + 2, 1, 0.05, 0.5)] })); const res = validateNestedProcedureV1(folds); assert.equal(res.status, 'NOT_VALIDATED_V1'); assert(res.rejectionReasons.includes('GLOBAL_BRIER_SKILL_NOT_POSITIVE')); });
test('Global LogLossSkill gate is independent from positive BrierSkill', () => { const pattern = [[0, 0.01], [0, 0.05], [0, 0.1], [1, 0.1]]; const folds = Array.from({ length: 6 }, (_, i) => goodFold(i, { predictions: pattern.map(([y, p], j) => prediction(i * 100 + j + 1, y, p, 0.4)) })); const res = validateNestedProcedureV1(folds); assert(res.globalBrierSkill > 0); assert(res.globalLogLossSkill <= 0); assert.equal(res.status, 'NOT_VALIDATED_V1'); assert(res.rejectionReasons.includes('GLOBAL_LOGLOSS_SKILL_NOT_POSITIVE')); });
test('Median outer proper-score gate rejects when at least four of six folds are bad', () => { const folds = sixGood(); for (let i = 0; i < 4; i++) folds[i].predictions = [prediction(i * 100 + 1, 0, 0.9, 0.5), prediction(i * 100 + 2, 1, 0.1, 0.5)]; for (let i = 4; i < 6; i++) { const rows = []; for (let j = 0; j < 100; j++) rows.push(prediction(i * 1000 + j + 1, j % 2, j % 2 ? 0.9 : 0.1, 0.5)); folds[i].predictions = rows; } const res = validateNestedProcedureV1(folds); assert(res.globalBrierSkill > 0); assert(res.globalLogLossSkill > 0); assert(res.medianOuterBrierSkill <= 0); assert(res.medianOuterLogLossSkill <= 0); assert.equal(res.status, 'NOT_VALIDATED_V1'); assert(res.rejectionReasons.includes('MEDIAN_OUTER_BRIER_SKILL_NOT_POSITIVE')); assert(res.rejectionReasons.includes('MEDIAN_OUTER_LOGLOSS_SKILL_NOT_POSITIVE')); });
test('AUC is diagnostic only and poor AUC alone does not reject', () => { const folds = Array.from({ length: 6 }, (_, i) => goodFold(i, { predictions: [prediction(i * 100 + 1, 0, 0.5, 0.7, 0.5), prediction(i * 100 + 2, 1, 0.5, 0.7, 0.5)] })); const res = validateNestedProcedureV1(folds); assert.equal(res.diagnosticGlobalRawAuc, 0.5); assert.equal(res.diagnosticGlobalCalibratedAuc, 0.5); assert.equal(res.status, 'VALIDATED_V1'); });
test('All four proper-score gates positive => VALIDATED_V1 and global metrics are recomputed on concatenated OOS', () => { const res = validateNestedProcedureV1(sixGood()); assert.equal(res.status, 'VALIDATED_V1'); assert(res.globalBrierSkill > 0); assert(res.globalLogLossSkill > 0); assert(res.medianOuterBrierSkill > 0); assert(res.medianOuterLogLossSkill > 0); assert.equal(res.rejectionReasons.length, 0); });
