import test from 'node:test';
import assert from 'node:assert/strict';
import { selectLabelCandidateV1, evaluateGate0V1 } from '../dist/quant-core/selection/selector.js';

function pred(t, y, raw = y ? 0.8 : 0.2, cal = y ? 0.8 : 0.2, base = 0.5) { return { decisionTime: t, actualLabel: y, rawProbability: raw, calibratedProbability: cal, baselineProbability: base, asset: 'XAUUSD' }; }
function fold(id, offset, overrides = {}) { const predictions = overrides.oosPredictions ?? [pred(offset + 1, 0), pred(offset + 2, 1)]; return { innerFoldId: id, trainCount: 100, calibrationCount: 20, oosCount: predictions.length, trainClass0: 50, trainClass1: 50, calibrationClass0: 10, calibrationClass1: 10, lineageValid: true, windowsValid: true, lockboxValid: true, requiredEvidencePresent: true, calibratedBrierSkill: 0.1, calibratedLogLossSkill: 0.1, oosPredictions: predictions, ...overrides }; }
function candidate(h = 3, tau = 0, overrides = {}) { return { h, tau, folds: [fold('IF1', 0), fold('IF2', 10), fold('IF3', 20)], aggregateRawMetrics: { brier: 0.2, logLoss: 0.5, ece: 0.05, auc: 0.7 }, aggregateCalibratedMetrics: { brier: 0.18, logLoss: 0.45, ece: 0.04, auc: 0.7 }, aggregateBaselineMetrics: { brier: 0.25, logLoss: 0.69, ece: 0.1, auc: 0.5 }, aggregateCalibratedBrierSkill: 0.2, aggregateCalibratedLogLossSkill: 0.2, aggregateInnerOOSRetentionRate: 0.8, ...overrides }; }

test('Gate 0 rejects empty/single-class/invalid structural evidence', () => { const g = evaluateGate0V1(candidate(3, 0, { folds: [fold('BAD1', 0, { trainCount: 0, trainClass1: 0, lineageValid: false }), fold('BAD2', 10), fold('BAD3', 20)] })); assert.equal(g.pass, false); assert(g.reasons.some((r) => r.startsWith('EMPTY_TRAIN'))); assert(g.reasons.some((r) => r.startsWith('SINGLE_CLASS_TRAIN'))); assert(g.reasons.some((r) => r.startsWith('LINEAGE_VIOLATION'))); });
test('Gate 0 rejects candidates missing any of the three preregistered Inner folds', () => { const g = evaluateGate0V1(candidate(3, 0, { folds: [fold('IF1', 0), fold('IF2', 10)] })); assert.equal(g.pass, false); assert(g.reasons.includes('INNER_FOLD_COUNT_MISMATCH')); });
test('Gate 0 rejects nonfinite predictions and duplicate Inner OOS decision times', () => { const g = evaluateGate0V1(candidate(3, 0, { folds: [fold('IF1', 0, { oosPredictions: [pred(1, 0), pred(2, 1, Number.NaN)] }), fold('IF2', 10, { oosPredictions: [pred(1, 0), pred(12, 1)] }), fold('IF3', 20)] })); assert.equal(g.pass, false); assert(g.reasons.some((r) => r.startsWith('NONFINITE_PREDICTION'))); assert(g.reasons.some((r) => r.startsWith('DUPLICATE_INNER_OOS_PREDICTION'))); });
test('Gate 0 allows a single-class individual OOS fold when aggregate Inner OOS is biclass', () => { const c = candidate(3, 0, { folds: [fold('IF1', 0, { oosPredictions: [pred(1, 0), pred(2, 0)] }), fold('IF2', 10, { oosPredictions: [pred(11, 1), pred(12, 1)] }), fold('IF3', 20, { oosPredictions: [pred(21, 0), pred(22, 1)] })] }); assert.equal(evaluateGate0V1(c).pass, true); });
test('Gate 1 requires both calibrated aggregate skills strictly > 0', () => { assert.equal(selectLabelCandidateV1([candidate(3, 0, { aggregateCalibratedBrierSkill: 0 })]).status, 'NO_VALID_LABEL_SPEC_V1'); });
test('Gate 2 uses the standard median of per-fold calibrated skills', () => { const pass = candidate(3, 0, { folds: [fold('IF1', 0, { calibratedBrierSkill: -0.1, calibratedLogLossSkill: -0.1 }), fold('IF2', 10, { calibratedBrierSkill: 0.1, calibratedLogLossSkill: 0.1 }), fold('IF3', 20, { calibratedBrierSkill: 0.2, calibratedLogLossSkill: 0.2 })] }); assert.equal(selectLabelCandidateV1([pass]).status, 'SELECTED'); const fail = candidate(3, 0, { folds: [fold('IF1', 0, { calibratedBrierSkill: -0.2, calibratedLogLossSkill: -0.2 }), fold('IF2', 10, { calibratedBrierSkill: -0.1, calibratedLogLossSkill: -0.1 }), fold('IF3', 20, { calibratedBrierSkill: 0.5, calibratedLogLossSkill: 0.5 })] }); assert.equal(selectLabelCandidateV1([fail]).status, 'NO_VALID_LABEL_SPEC_V1'); });
test('Gate 3 requires aggregate raw AUC strictly > 0.5', () => { assert.equal(selectLabelCandidateV1([candidate(3, 0, { aggregateRawMetrics: { brier: 0.2, logLoss: 0.5, ece: 0.05, auc: 0.5 } })]).status, 'NO_VALID_LABEL_SPEC_V1'); });
test('Pareto stage removes exactly dominated candidates', () => { const a = candidate(3, 0, { aggregateCalibratedBrierSkill: 0.3, aggregateCalibratedLogLossSkill: 0.3, aggregateInnerOOSRetentionRate: 0.9, aggregateRawMetrics: { brier: 0.2, logLoss: 0.5, ece: 0.05, auc: 0.8 } }); const b = candidate(6, 0, { aggregateCalibratedBrierSkill: 0.2, aggregateCalibratedLogLossSkill: 0.2, aggregateInnerOOSRetentionRate: 0.8, aggregateRawMetrics: { brier: 0.2, logLoss: 0.5, ece: 0.05, auc: 0.7 } }); const res = selectLabelCandidateV1([a, b]); assert.deepEqual(res.paretoFrontier, [{ h: 3, tau: 0 }]); assert.deepEqual(res.selected, { h: 3, tau: 0 }); });
test('Common Support only compares same h and can remove lower-retention tau without refit', () => { const commonA = [pred(1, 0, 0.1, 0.1), pred(2, 1, 0.9, 0.9), pred(3, 0, 0.2, 0.2), pred(4, 1, 0.8, 0.8)]; const commonB = [pred(1, 0, 0.05, 0.05), pred(2, 1, 0.95, 0.95), pred(3, 0, 0.1, 0.1), pred(4, 1, 0.9, 0.9), pred(5, 1, 0.8, 0.8)]; const a = candidate(12, 0.0004, { aggregateCalibratedBrierSkill: 0.3, aggregateCalibratedLogLossSkill: 0.3, aggregateInnerOOSRetentionRate: 0.7, folds: [fold('A1', 0, { oosPredictions: commonA }), fold('A2', 100), fold('A3', 200)] }); const b = candidate(12, 0.0002, { aggregateCalibratedBrierSkill: 0.2, aggregateCalibratedLogLossSkill: 0.2, aggregateInnerOOSRetentionRate: 0.9, aggregateRawMetrics: { brier: 0.2, logLoss: 0.5, ece: 0.05, auc: 0.75 }, folds: [fold('B1', 0, { oosPredictions: commonB }), fold('B2', 300), fold('B3', 400)] }); const res = selectLabelCandidateV1([a, b]); assert.deepEqual(res.paretoFrontier, [{ h: 12, tau: 0.0004 }, { h: 12, tau: 0.0002 }]); assert.deepEqual(res.postCommonSupportFrontier, [{ h: 12, tau: 0.0002 }]); assert.deepEqual(res.selected, { h: 12, tau: 0.0002 }); });
test('Common Support never compares across different h', () => { const a = candidate(3, 0, { aggregateCalibratedBrierSkill: 0.3, aggregateInnerOOSRetentionRate: 0.7 }); const b = candidate(6, 0, { aggregateCalibratedBrierSkill: 0.2, aggregateInnerOOSRetentionRate: 0.9, aggregateRawMetrics: { brier: 0.2, logLoss: 0.5, ece: 0.05, auc: 0.75 } }); assert.equal(selectLabelCandidateV1([a, b]).postCommonSupportFrontier.length, 2); });
test('Tie-break is max retention, then min tau, then min h using exact equality', () => { const res = selectLabelCandidateV1([candidate(6, 0.0004, { aggregateInnerOOSRetentionRate: 0.8 }), candidate(6, 0.0002, { aggregateInnerOOSRetentionRate: 0.8 }), candidate(3, 0.0002, { aggregateInnerOOSRetentionRate: 0.8 })]); assert.deepEqual(res.selected, { h: 3, tau: 0.0002 }); });
